### ISSUE TITLE
create ficus app stoped working

### ISSUE THREAD

**Issue by vic-cekvenich** [ficusjs/create-ficus-app#25]
It used to work. Is there an eta?

**Comment by ducksoupdev** [comment]
Sorry for the delay, I'll investigate and let you know

**Comment by vic-cekvenich** [comment]
(also I would not be upset if you create an example w/ 11ty and pug like https://gitlab.com/cekvenich2/11pug but w/ ficus)

**Comment by ducksoupdev** [comment]
This is fixed in v1.4.1
