### ISSUE TITLE
feature request: switch 11ty example to be based on pug

### ISSUE THREAD

**Issue by vic-cekvenich** [ficusjs/create-ficus-app#31]
Hi, we are using this lib and adding new projects. New people have a harder time converting the 11ty to pug, and pug is much cleaner and more popular.

**Comment by vic-cekvenich** [comment]
Or come up with another example, 11ty pug on top please.

**Comment by ducksoupdev** [comment]
@vic-cekvenich apologies for the delay in responding. Would you be happy to create a version of the 11ty template based on Pug? Having not had experience of using Pug, I'm not best placed to do that.
